### ISSUE TITLE
pulling wrong column for raw counts

### ISSUE THREAD

**Issue by ebergelson** [SeedlingsBabylab/wordcompare#2]
this may be a parseclan issue rather than a wordcompare issue but when reading in the raw counts, instead of reading in the basic_level column, wordcompare reads in the comments column: seems like it's hardcoded by position rather than by header.
[sample file: 27_07_processed.csv has the columns in the order parseclan produces, 27_07_coderDL_ready_for_check.csv has them in the order wordcompare wants]

**Comment by andreiamatuni** [comment]
I think this may be due to earlier versions of parse_clan. I recently rewrote parts of it to change the column order that it produces. Running 27_07_coderDL_processed.csv through the latest parse_clan produces output that's similar to the ready_for_check version you mentioned. It outputs an empty basic level column and the comments column is full of NA's. Are you sure you're running the latest parse_clan?

**Comment by andreiamatuni** [comment]
I meant to say running 27_07_coderDL.cex through the latest parse_clan

**Comment by ebergelson** [comment]
you are right. i had the latest wordcompare but not the latest parseclan. sorrrryy.

**Comment by andreiamatuni** [comment]
ok cool, going to close this issue for now.
